version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d



  user-service:
    build: ./user_service
    volumes: 
      - ./user_service:/usr/src/app
      #- ./data:/usr/src/app/data
    ports: 
      - 1337:80
    links:
      - db
    depends_on:
      - db
      


  website:
    build: ./website
    volumes:
      - ./website:/var/www/html
      #- ./data:/var/www/html/user/data
    ports:
      - 5000:80
    depends_on:
      - user-service  
      - db
    links:
      - db