version: "3"

services:
  login-service:
    build: ./login_service
    volumes:
      - ./login_service:/usr/src/app
    ports:
      - 5001:80



  website:
    image: php:7.3-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - login-service


  