version: "3"

services:
  meta-service:
    build: ./metadata_service
    volumes: 
      - ./metadata_service:/usr/src/app
    ports:
      - 53122:80



  website:
    image: php:7.3-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - meta-service


  