version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d



  user-service:
    build: ./user_service
    volumes: 
      - ./user_service:/usr/src/app
    ports: 
      - 6000:80
    links:
      - db
    depends_on:
      - db


  
  meta-service:
    build: ./metadata_service
    volumes: 
      - ./metadata_service:/usr/src/app
    ports:
      - 53122:80



  website:
    image: php:7.3-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - meta-service
      - user-service


  