CREATE DATABASE IF NOT EXISTS ip;
USE ip;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY_KEY (id)
) ENGINE=INNODB